// Sentence pattern practice — fill in the Japanese sentence for the given English meaning.
// Sentences use verbs from vocab-data.js, grouped loosely by grammar pattern (pattern is just
// a label for reference, not used by the game logic). Covers all words from vocab-data.js,
// each in whichever pattern(s) it fits naturally (not every word fits every pattern).
window.SENTENCE_PRACTICE = [
  // ~のが好きです (dictionary form) — "I like doing ~"
  {pattern:"のが好きです", en:"I like swimming.", jp:"泳ぐのが好きです。", kana:"およぐのがすきです。"},
  {pattern:"のが好きです", en:"I like cooking.", jp:"りょうりするのが好きです。", kana:"りょうりするのがすきです。"},
  {pattern:"のが好きです", en:"I like walking.", jp:"歩くのが好きです。", kana:"あるくのがすきです。"},
  {pattern:"のが好きです", en:"I like taking photos.", jp:"写真を撮るのが好きです。", kana:"しゃしんをとるのがすきです。"},
  {pattern:"のが好きです", en:"I like speaking in English.", jp:"英語で話すのが好きです。", kana:"えいごではなすのがすきです。"},
  {pattern:"のが好きです", en:"I like listening to music.", jp:"音楽を聞くのが好きです。", kana:"おんがくをきくのがすきです。"},
  {pattern:"のが好きです", en:"I like making food.", jp:"料理を作るのが好きです。", kana:"りょうりをつくるのがすきです。"},
  {pattern:"のが好きです", en:"I like traveling.", jp:"旅行するのが好きです。", kana:"りょこうするのがすきです。"},
  {pattern:"のが好きです", en:"I like playing in the park.", jp:"公園で遊ぶのが好きです。", kana:"こうえんであそぶのがすきです。"},
  {pattern:"のが好きです", en:"I like teaching.", jp:"教えるのが好きです。", kana:"おしえるのがすきです。"},
  {pattern:"のが好きです", en:"I like playing the piano.", jp:"ピアノを弾くのが好きです。", kana:"ピアノをひくのがすきです。"},
  {pattern:"のが好きです", en:"I like collecting stamps.", jp:"切手を集めるのが好きです。", kana:"きってをあつめるのがすきです。"},

  // ~つもりです (dictionary form) — "I plan to / intend to ~"
  {pattern:"つもりです", en:"I plan to travel next year.", jp:"来年、旅行するつもりです。", kana:"らいねん、りょこうするつもりです。"},
  {pattern:"つもりです", en:"I plan to clean my room this weekend.", jp:"週末に部屋を掃除するつもりです。", kana:"しゅうまつにへやをそうじするつもりです。"},
  {pattern:"つもりです", en:"The two of them plan to get married next year.", jp:"二人は来年結婚するつもりです。", kana:"ふたりはらいねんけっこんするつもりです。"},
  {pattern:"つもりです", en:"I plan to graduate this year.", jp:"今年卒業するつもりです。", kana:"ことしそつぎょうするつもりです。"},
  {pattern:"つもりです", en:"I plan to go to Japan next month.", jp:"来月、日本に行くつもりです。", kana:"らいげつ、にほんにいくつもりです。"},
  {pattern:"つもりです", en:"I plan to go out in the afternoon.", jp:"午後、出かけるつもりです。", kana:"ごご、でかけるつもりです。"},
  {pattern:"つもりです", en:"I plan to take the test next week.", jp:"来週、テストをうけるつもりです。", kana:"らいしゅう、テストをうけるつもりです。"},
  {pattern:"つもりです", en:"I plan to meet my friend tomorrow.", jp:"明日、友達にあうつもりです。", kana:"あした、ともだちにあうつもりです。"},
  {pattern:"つもりです", en:"I plan to go home early.", jp:"早く帰るつもりです。", kana:"はやくかえるつもりです。"},
  {pattern:"つもりです", en:"I plan to pay later.", jp:"後でお金を払うつもりです。", kana:"あとでおかねをはらうつもりです。"},
  {pattern:"つもりです", en:"I plan to live in Osaka next year.", jp:"来年、大阪にすむつもりです。", kana:"らいねん、おおさかにすむつもりです。"},
  {pattern:"つもりです", en:"I plan to contact the teacher tomorrow.", jp:"明日、先生に連絡するつもりです。", kana:"あした、せんせいにれんらくするつもりです。"},
  {pattern:"つもりです", en:"I plan to take my child to the zoo.", jp:"子供を動物園に連れていくつもりです。", kana:"こどもをどうぶつえんにつれていくつもりです。"},
  {pattern:"つもりです", en:"I plan to change the schedule.", jp:"予定を変えるつもりです。", kana:"よていをかえるつもりです。"},
  {pattern:"つもりです", en:"I plan to quit my job next month.", jp:"来月、仕事を辞めるつもりです。", kana:"らいげつ、しごとをやめるつもりです。"},
  {pattern:"つもりです", en:"I plan to tidy my room this weekend.", jp:"週末に部屋を片付けるつもりです。", kana:"しゅうまつにへやをかたづけるつもりです。"},
  {pattern:"つもりです", en:"I plan to leave the house at 9.", jp:"9時に家を出るつもりです。", kana:"くじにいえをでるつもりです。"},
  {pattern:"つもりです", en:"I plan to do laundry this weekend.", jp:"週末に洗濯するつもりです。", kana:"しゅうまつにせんたくするつもりです。"},
  {pattern:"つもりです", en:"I plan to serve as manager next year.", jp:"来年、部長を務めるつもりです。", kana:"らいねん、ぶちょうをつとめるつもりです。"},
  {pattern:"つもりです", en:"I plan to start going to the gym next month.", jp:"来月から、ジムに通うつもりです。", kana:"らいげつから、ジムにかようつもりです。"},
  {pattern:"つもりです", en:"I plan to apply next week.", jp:"来週、もうしこみするつもりです。", kana:"らいしゅう、もうしこみするつもりです。"},

  // ~前に (dictionary form) — "before doing ~"
  {pattern:"前に", en:"Before eating, I wash my hands.", jp:"食べる前に、手を洗います。", kana:"たべるまえに、てをあらいます。"},
  {pattern:"前に", en:"Before going out, I lock the door.", jp:"出かける前に、かぎをかけます。", kana:"でかけるまえに、かぎをかけます。"},
  {pattern:"前に", en:"Before going home, I'll meet my friend.", jp:"帰る前に、友達に会います。", kana:"かえるまえに、ともだちにあいます。"},
  {pattern:"前に", en:"Before cleaning, I open the windows.", jp:"掃除する前に、窓を開けます。", kana:"そうじするまえに、まどをあけます。"},
  {pattern:"前に", en:"Before going, I look at a map.", jp:"行く前に、地図を見ます。", kana:"いくまえに、ちずをみます。"},
  {pattern:"前に", en:"Before getting on the train, I buy a ticket.", jp:"電車に乗る前に、切符を買います。", kana:"でんしゃにのるまえに、きっぷをかいます。"},
  {pattern:"前に", en:"Before turning off the TV, I'll watch once more.", jp:"テレビを消す前に、もう一度見ます。", kana:"テレビをけすまえに、もういちどみます。"},
  {pattern:"前に", en:"Before climbing the mountain, I bring water.", jp:"山にのぼる前に、水を持っていきます。", kana:"やまにのぼるまえに、みずをもっていきます。"},
  {pattern:"前に", en:"Before sleeping, I take a shower.", jp:"寝る前に、シャワーを浴びます。", kana:"ねるまえに、シャワーをあびます。"},
  {pattern:"前に", en:"Before entering the room, I knock.", jp:"部屋に入る前に、ノックします。", kana:"へやにはいるまえに、ノックします。"},
  {pattern:"前に", en:"Before sleeping, I brush my teeth.", jp:"寝る前に、歯を磨きます。", kana:"ねるまえに、はをみがきます。"},
  {pattern:"前に", en:"Before leaving the house, I turn off the lights.", jp:"家を出る前に、電気を消します。", kana:"いえをでるまえに、でんきをけします。"},

  // ~ましょうか (ます stem) — "Shall we ~?"
  {pattern:"ましょうか", en:"Shall we watch a movie?", jp:"映画を見ましょうか。", kana:"えいがをみましょうか。"},
  {pattern:"ましょうか", en:"Shall we eat lunch?", jp:"昼ご飯を食べましょうか。", kana:"ひるごはんをたべましょうか。"},
  {pattern:"ましょうか", en:"Shall we go out?", jp:"出かけましょうか。", kana:"でかけましょうか。"},
  {pattern:"ましょうか", en:"Shall we clean the room?", jp:"部屋を掃除しましょうか。", kana:"へやをそうじしましょうか。"},
  {pattern:"ましょうか", en:"Shall we check the weather?", jp:"天気をチェックしましょうか。", kana:"てんきをチェックしましょうか。"},
  {pattern:"ましょうか", en:"Shall we wash the dishes?", jp:"お皿を洗いましょうか。", kana:"おさらをあらいましょうか。"},
  {pattern:"ましょうか", en:"Shall we head home soon?", jp:"そろそろ帰りましょうか。", kana:"そろそろかえりましょうか。"},
  {pattern:"ましょうか", en:"Shall I carry your bag?", jp:"かばんをもちましょうか。", kana:"かばんをもちましょうか。"},
  {pattern:"ましょうか", en:"Shall we decide where to go?", jp:"どこに行くか、きめましょうか。", kana:"どこにいくか、きめましょうか。"},

  // plain ます form — polite present/future statement
  {pattern:"ます form", en:"I walk every day.", jp:"毎日、歩きます。", kana:"まいにち、あるきます。"},
  {pattern:"ます form", en:"I will travel tomorrow.", jp:"明日、旅行します。", kana:"あした、りょこうします。"},
  {pattern:"ます form", en:"I do laundry on weekends.", jp:"週末に洗濯します。", kana:"しゅうまつにせんたくします。"},
  {pattern:"ます form", en:"I welcome my friend into my home.", jp:"友達を家に迎えます。", kana:"ともだちをいえにむかえます。"},
  {pattern:"ます form", en:"I go out on Saturdays.", jp:"土曜日に出かけます。", kana:"どようびにでかけます。"},

  // ~たいです (ます stem) — "I want to ~"
  {pattern:"たいです", en:"I want to go to Japan.", jp:"日本に行きたいです。", kana:"にほんにいきたいです。"},
  {pattern:"たいです", en:"I want to buy a new car.", jp:"新しい車を買いたいです。", kana:"あたらしいくるまをかいたいです。"},
  {pattern:"たいです", en:"I want to memorize kanji.", jp:"漢字を覚えたいです。", kana:"かんじをおぼえたいです。"},
  {pattern:"たいです", en:"I want to invite my friend.", jp:"友達を誘いたいです。", kana:"ともだちをさそいたいです。"},
  {pattern:"たいです", en:"I want to drink coffee.", jp:"コーヒーを飲みたいです。", kana:"コーヒーをのみたいです。"},
  {pattern:"たいです", en:"I want to help my friend.", jp:"友達を手伝いたいです。", kana:"ともだちをてつだいたいです。"},
  {pattern:"たいです", en:"I want to write a letter.", jp:"手紙を書きたいです。", kana:"てがみをかきたいです。"},
  {pattern:"たいです", en:"I want to withdraw money.", jp:"お金をおろしたいです。", kana:"おかねをおろしたいです。"},
  {pattern:"たいです", en:"I want to ride the shinkansen.", jp:"新幹線に乗りたいです。", kana:"しんかんせんにのりたいです。"},
  {pattern:"たいです", en:"I want to climb the mountain.", jp:"山にのぼりたいです。", kana:"やまにのぼりたいです。"},
  {pattern:"たいです", en:"I want to pickle vegetables.", jp:"野菜を漬けたいです。", kana:"やさいをつけたいです。"},
  {pattern:"たいです", en:"I want to use the computer.", jp:"パソコンを使いたいです。", kana:"パソコンをつかいたいです。"},
  {pattern:"たいです", en:"I want to borrow a book.", jp:"本を借りたいです。", kana:"ほんをかりたいです。"},
  {pattern:"たいです", en:"I want to ask the teacher.", jp:"先生にたずねたいです。", kana:"せんせいにたずねたいです。"},
  {pattern:"たいです", en:"I want to change my hairstyle.", jp:"髪型を変えたいです。", kana:"かみがたをかえたいです。"},
  {pattern:"たいです", en:"I want to choose a present.", jp:"プレゼントを選びたいです。", kana:"プレゼントをえらびたいです。"},
  {pattern:"たいです", en:"I want to ask for help.", jp:"助けを頼みたいです。", kana:"たすけをたのみたいです。"},
  {pattern:"たいです", en:"I want to know the answer.", jp:"答えを知りたいです。", kana:"こたえをしりたいです。"},
  {pattern:"たいです", en:"I want to order pizza.", jp:"ピザを注文したいです。", kana:"ピザをちゅうもんしたいです。"},
  {pattern:"たいです", en:"I want to do my homework.", jp:"宿題をやりたいです。", kana:"しゅくだいをやりたいです。"},

  // ~すぎました (ます stem) — "did too much of ~"
  {pattern:"すぎました", en:"I ate too much yesterday.", jp:"昨日、食べすぎました。", kana:"きのう、たべすぎました。"},
  {pattern:"すぎました", en:"I drank too much alcohol.", jp:"お酒を飲みすぎました。", kana:"おさけをのみすぎました。"},
  {pattern:"すぎました", en:"I walked too much today.", jp:"今日は歩きすぎました。", kana:"きょうはあるきすぎました。"},
  {pattern:"すぎました", en:"I worked too much last night.", jp:"昨夜、働きすぎました。", kana:"ゆうべ、はたらきすぎました。"},
  {pattern:"すぎました", en:"I bought too many clothes.", jp:"服を買いすぎました。", kana:"ふくをかいすぎました。"},
  {pattern:"すぎました", en:"I swam too much today.", jp:"今日は泳ぎすぎました。", kana:"きょうはおよぎすぎました。"},
  {pattern:"すぎました", en:"I cut my hair too much.", jp:"髪を切りすぎました。", kana:"かみをきりすぎました。"},
  {pattern:"すぎました", en:"I hurried too much.", jp:"急ぎすぎました。", kana:"いそぎすぎました。"},
  {pattern:"すぎました", en:"I collected too many books.", jp:"本を集めすぎました。", kana:"ほんをあつめすぎました。"},
  {pattern:"すぎました", en:"I added too much sugar.", jp:"砂糖を入れすぎました。", kana:"さとうをいれすぎました。"},
  {pattern:"すぎました", en:"I paid too much money.", jp:"お金を出しすぎました。", kana:"おかねをだしすぎました。"},

  // て form + ください — "please do ~"
  {pattern:"てください", en:"Please open the door.", jp:"ドアを開けてください。", kana:"ドアをあけてください。"},
  {pattern:"てください", en:"Please close the window.", jp:"窓を閉めてください。", kana:"まどをしめてください。"},
  {pattern:"てください", en:"Please help me.", jp:"手伝ってください。", kana:"てつだってください。"},
  {pattern:"てください", en:"Please sit here.", jp:"ここに座ってください。", kana:"ここにすわってください。"},
  {pattern:"てください", en:"Please take this class.", jp:"このクラスをうけてください。", kana:"このクラスをうけてください。"},
  {pattern:"てください", en:"Please check the email.", jp:"メールをチェックしてください。", kana:"メールをチェックしてください。"},
  {pattern:"てください", en:"Please call later.", jp:"後で電話してください。", kana:"あとででんわしてください。"},
  {pattern:"てください", en:"Please wash your hands.", jp:"手を洗ってください。", kana:"てをあらってください。"},
  {pattern:"てください", en:"Please cut the paper.", jp:"紙を切ってください。", kana:"かみをきってください。"},
  {pattern:"てください", en:"Please turn on the light.", jp:"電気をつけてください。", kana:"でんきをつけてください。"},
  {pattern:"てください", en:"Please turn off the TV.", jp:"テレビを消してください。", kana:"テレビをけしてください。"},
  {pattern:"てください", en:"Please lend me a pen.", jp:"ペンを貸してください。", kana:"ペンをかしてください。"},
  {pattern:"てください", en:"Please hold the luggage.", jp:"荷物をもってください。", kana:"にもつをもってください。"},
  {pattern:"てください", en:"Please pay here.", jp:"ここでお金を払ってください。", kana:"ここでおかねをはらってください。"},
  {pattern:"てください", en:"Please put the sauce on.", jp:"ソースをかけてください。", kana:"ソースをかけてください。"},
  {pattern:"てください", en:"Please teach me Japanese.", jp:"日本語を教えてください。", kana:"にほんごをおしえてください。"},
  {pattern:"てください", en:"Please show me your passport.", jp:"パスポートを見せてください。", kana:"パスポートをみせてください。"},
  {pattern:"てください", en:"Please hurry.", jp:"急いでください。", kana:"いそいでください。"},
  {pattern:"てください", en:"Please contact me later.", jp:"後で連絡してください。", kana:"あとでれんらくしてください。"},
  {pattern:"てください", en:"Please say it again.", jp:"もう一度いってください。", kana:"もういちどいってください。"},
  {pattern:"てください", en:"Please translate this sentence.", jp:"この文を訳してください。", kana:"このぶんをやくしてください。"},
  {pattern:"てください", en:"Please bring water.", jp:"お水を持ってきてください。", kana:"おみずをもってきてください。"},
  {pattern:"てください", en:"Please bring your friend.", jp:"友達を連れてきてください。", kana:"ともだちをつれてきてください。"},
  {pattern:"てください", en:"Please give me a ride in the car.", jp:"私を車に乗せてください。", kana:"わたしをくるまにのせてください。"},
  {pattern:"てください", en:"Please take an umbrella.", jp:"傘を持っていってください。", kana:"かさをもっていってください。"},
  {pattern:"てください", en:"Please move the desk.", jp:"机を動かしてください。", kana:"つくえをうごかしてください。"},
  {pattern:"てください", en:"Please add sugar.", jp:"砂糖を入れてください。", kana:"さとうをいれてください。"},
  {pattern:"てください", en:"Please tidy the room.", jp:"部屋を片付けてください。", kana:"へやをかたづけてください。"},
  {pattern:"てください", en:"Please choose your favorite color.", jp:"好きな色を選んでください。", kana:"すきないろをえらんでください。"},
  {pattern:"てください", en:"Please pick me up at the station.", jp:"駅で迎えてください。", kana:"えきでむかえてください。"},
  {pattern:"てください", en:"Please submit your homework.", jp:"宿題を出してください。", kana:"しゅくだいをだしてください。"},
  {pattern:"てください", en:"Please brush your teeth.", jp:"歯を磨いてください。", kana:"はをみがいてください。"},
  {pattern:"てください", en:"Please memorize this word.", jp:"この単語を覚えてください。", kana:"このたんごをおぼえてください。"},
  {pattern:"てください", en:"Please invite your friend.", jp:"友達を誘ってください。", kana:"ともだちをさそってください。"},
  {pattern:"てください", en:"Please order coffee.", jp:"コーヒーを頼んでください。", kana:"コーヒーをたのんでください。"},
  {pattern:"てください", en:"Please fix the computer.", jp:"パソコンをなおしてください。", kana:"パソコンをなおしてください。"},
  {pattern:"てください", en:"Please apply here.", jp:"ここでもうしこみしてください。", kana:"ここでもうしこみしてください。"},
  {pattern:"てください", en:"Please decide the schedule.", jp:"予定をきめてください。", kana:"よていをきめてください。"},
  {pattern:"てください", en:"Please do this.", jp:"これをやってください。", kana:"これをやってください。"},
  {pattern:"てください", en:"Please order coffee (at a shop).", jp:"コーヒーを注文してください。", kana:"コーヒーをちゅうもんしてください。"},

  // て form + いただけませんか — polite request "could you please ~"
  {pattern:"ていただけませんか", en:"Could you please help me?", jp:"手伝っていただけませんか。", kana:"てつだっていただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please open the window?", jp:"窓を開けていただけませんか。", kana:"まどをあけていただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please say that again?", jp:"もう一度話していただけませんか。", kana:"もういちどはなしていただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please lend it to me?", jp:"貸していただけませんか。", kana:"かしていただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please translate this?", jp:"これを訳していただけませんか。", kana:"これをやくしていただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please fix the car?", jp:"車をなおしていただけませんか。", kana:"くるまをなおしていただけませんか。"},

  // て form + もいいですか — "may I ~?"
  {pattern:"てもいいですか", en:"May I sit here?", jp:"ここに座ってもいいですか。", kana:"ここにすわってもいいですか。"},
  {pattern:"てもいいですか", en:"May I use this?", jp:"これを使ってもいいですか。", kana:"これをつかってもいいですか。"},
  {pattern:"てもいいですか", en:"May I take a photo?", jp:"写真を撮ってもいいですか。", kana:"しゃしんをとってもいいですか。"},
  {pattern:"てもいいですか", en:"May I turn on the TV?", jp:"テレビをつけてもいいですか。", kana:"テレビをつけてもいいですか。"},
  {pattern:"てもいいですか", en:"May I watch this video?", jp:"このビデオを見てもいいですか。", kana:"このビデオをみてもいいですか。"},
  {pattern:"てもいいですか", en:"May I close the window?", jp:"窓を閉めてもいいですか。", kana:"まどをしめてもいいですか。"},
  {pattern:"てもいいですか", en:"May I ask a question?", jp:"質問を聞いてもいいですか。", kana:"しつもんをきいてもいいですか。"},
  {pattern:"てもいいですか", en:"May I come in?", jp:"入ってもいいですか。", kana:"はいってもいいですか。"},
  {pattern:"てもいいですか", en:"May I borrow an umbrella?", jp:"傘を借りてもいいですか。", kana:"かさをかりてもいいですか。"},
  {pattern:"てもいいですか", en:"May I ask a question? (formal)", jp:"質問をたずねてもいいですか。", kana:"しつもんをたずねてもいいですか。"},
  {pattern:"てもいいですか", en:"May I show you a photo?", jp:"写真を見せてもいいですか。", kana:"しゃしんをみせてもいいですか。"},
  {pattern:"てもいいですか", en:"May I smoke here?", jp:"ここでタバコをすってもいいですか。", kana:"ここでタバコをすってもいいですか。"},

  // て form + います — ongoing / habitual action
  {pattern:"ています", en:"I am cleaning now.", jp:"今、掃除しています。", kana:"いま、そうじしています。"},
  {pattern:"ています", en:"I work at a bank.", jp:"銀行で働いています。", kana:"ぎんこうではたらいています。"},
  {pattern:"ています", en:"I am on the phone now.", jp:"今、電話しています。", kana:"いま、でんわしています。"},
  {pattern:"ています", en:"I walk in the park every morning.", jp:"毎朝、公園を歩いています。", kana:"まいあさ、こうえんをあるいています。"},
  {pattern:"ています", en:"I am cooking dinner now.", jp:"今、晩ご飯をりょうりしています。", kana:"いま、ばんごはんをりょうりしています。"},
  {pattern:"ています", en:"I am making dinner now.", jp:"今、晩ご飯を作っています。", kana:"いま、ばんごはんをつくっています。"},
  {pattern:"ています", en:"I am writing a report now.", jp:"今、レポートを書いています。", kana:"いま、レポートをかいています。"},
  {pattern:"ています", en:"I am taking photos now.", jp:"今、写真を撮っています。", kana:"いま、しゃしんをとっています。"},
  {pattern:"ています", en:"I live in Tokyo.", jp:"東京にすんでいます。", kana:"とうきょうにすんでいます。"},
  {pattern:"ています", en:"I am taking a shower now.", jp:"今、シャワーを浴びています。", kana:"いま、シャワーをあびています。"},
  {pattern:"ています", en:"I am looking for a job now.", jp:"今、仕事を探しています。", kana:"いま、しごとをさがしています。"},
  {pattern:"ています", en:"I am playing the guitar now.", jp:"今、ギターを弾いています。", kana:"いま、ギターをひいています。"},
  {pattern:"ています", en:"He serves as a teacher.", jp:"彼は先生を務めています。", kana:"かれはせんせいをつとめています。"},
  {pattern:"ています", en:"I commute to school every day.", jp:"毎日、学校に通っています。", kana:"まいにち、がっこうにかよっています。"},

  // て form + いました — past progressive
  {pattern:"ていました", en:"I was watching TV last night.", jp:"昨日の夜、テレビを見ていました。", kana:"きのうのよる、テレビをみていました。"},
  {pattern:"ていました", en:"I was cleaning my room at that time.", jp:"その時、部屋を掃除していました。", kana:"そのとき、へやをそうじしていました。"},
  {pattern:"ていました", en:"I used to swim a lot as a child.", jp:"子供の時、よく泳いでいました。", kana:"こどものとき、よくおよいでいました。"},
  {pattern:"ていました", en:"I was talking with her.", jp:"彼女と話していました。", kana:"かのじょとはなしていました。"},
  {pattern:"ていました", en:"The movie had already started.", jp:"映画はもう始まっていました。", kana:"えいがはもうはじまっていました。"},

  // まだ〜ていません — "haven't done ~ yet"
  {pattern:"まだ〜ていません", en:"I haven't cleaned yet.", jp:"まだ掃除していません。", kana:"まだそうじしていません。"},
  {pattern:"まだ〜ていません", en:"I haven't eaten yet.", jp:"まだ食べていません。", kana:"まだたべていません。"},
  {pattern:"まだ〜ていません", en:"I haven't graduated yet.", jp:"まだ卒業していません。", kana:"まだそつぎょうしていません。"},
  {pattern:"まだ〜ていません", en:"I haven't gotten married yet.", jp:"まだ結婚していません。", kana:"まだけっこんしていません。"},
  {pattern:"まだ〜ていません", en:"I haven't opened the door yet.", jp:"まだドアを開けていません。", kana:"まだドアをあけていません。"},
  {pattern:"まだ〜ていません", en:"I haven't quit my job yet.", jp:"まだ仕事を辞めていません。", kana:"まだしごとをやめていません。"},
  {pattern:"まだ〜ていません", en:"We haven't broken up yet.", jp:"まだ別れていません。", kana:"まだわかれていません。"},
  {pattern:"まだ〜ていません", en:"It hasn't started yet.", jp:"まだ始まっていません。", kana:"まだはじまっていません。"},
  {pattern:"まだ〜ていません", en:"This plant hasn't died yet.", jp:"この植物はまだ死んでいません。", kana:"このしょくぶつはまだしんでいません。"},

  // て form as connector — "I'll do X, then Y"
  {pattern:"て (connector)", en:"I'll eat breakfast, then go to school.", jp:"朝ご飯を食べて、学校に行きます。", kana:"あさごはんをたべて、がっこうにいきます。"},
  {pattern:"て (connector)", en:"I'll wash my hands, then eat.", jp:"手を洗って、食べます。", kana:"てをあらって、たべます。"},
  {pattern:"て (connector)", en:"I'll clean, then do laundry.", jp:"掃除して、洗濯します。", kana:"そうじして、せんたくします。"},
  {pattern:"て (connector)", en:"I'll call my friend, then go out.", jp:"友達に電話して、出かけます。", kana:"ともだちにでんわして、でかけます。"},
  {pattern:"て (connector)", en:"I'll go out, then come home late.", jp:"出かけて、遅く帰ります。", kana:"でかけて、おそくかえります。"}
];
