// Sentence pattern practice — fill in the Japanese sentence for the given English meaning.
// Sentences use verbs from vocab-data.js, grouped loosely by grammar pattern (pattern is just
// a label for reference, not used by the game logic). Covers all words from vocab-data.js,
// each in whichever pattern(s) it fits naturally (not every word fits every pattern).
window.SENTENCE_PRACTICE = [
  // ~のが好きです (dictionary form) — "I like doing ~"
  {pattern:"のが好きです", en:"I like swimming.", jp:"泳ぐのが好きです。"},
  {pattern:"のが好きです", en:"I like cooking.", jp:"りょうりするのが好きです。"},
  {pattern:"のが好きです", en:"I like walking.", jp:"歩くのが好きです。"},
  {pattern:"のが好きです", en:"I like taking photos.", jp:"写真を撮るのが好きです。"},
  {pattern:"のが好きです", en:"I like speaking in English.", jp:"英語で話すのが好きです。"},
  {pattern:"のが好きです", en:"I like listening to music.", jp:"音楽を聞くのが好きです。"},
  {pattern:"のが好きです", en:"I like making food.", jp:"料理を作るのが好きです。"},
  {pattern:"のが好きです", en:"I like traveling.", jp:"旅行するのが好きです。"},
  {pattern:"のが好きです", en:"I like playing in the park.", jp:"公園で遊ぶのが好きです。"},
  {pattern:"のが好きです", en:"I like teaching.", jp:"教えるのが好きです。"},
  {pattern:"のが好きです", en:"I like playing the piano.", jp:"ピアノを弾くのが好きです。"},
  {pattern:"のが好きです", en:"I like collecting stamps.", jp:"切手を集めるのが好きです。"},

  // ~つもりです (dictionary form) — "I plan to / intend to ~"
  {pattern:"つもりです", en:"I plan to travel next year.", jp:"来年、旅行するつもりです。"},
  {pattern:"つもりです", en:"I plan to clean my room this weekend.", jp:"週末に部屋を掃除するつもりです。"},
  {pattern:"つもりです", en:"The two of them plan to get married next year.", jp:"二人は来年結婚するつもりです。"},
  {pattern:"つもりです", en:"I plan to graduate this year.", jp:"今年卒業するつもりです。"},
  {pattern:"つもりです", en:"I plan to go to Japan next month.", jp:"来月、日本に行くつもりです。"},
  {pattern:"つもりです", en:"I plan to go out in the afternoon.", jp:"午後、出かけるつもりです。"},
  {pattern:"つもりです", en:"I plan to take the test next week.", jp:"来週、テストをうけるつもりです。"},
  {pattern:"つもりです", en:"I plan to meet my friend tomorrow.", jp:"明日、友達にあうつもりです。"},
  {pattern:"つもりです", en:"I plan to go home early.", jp:"早く帰るつもりです。"},
  {pattern:"つもりです", en:"I plan to pay later.", jp:"後でお金を払うつもりです。"},
  {pattern:"つもりです", en:"I plan to live in Osaka next year.", jp:"来年、大阪にすむつもりです。"},
  {pattern:"つもりです", en:"I plan to contact the teacher tomorrow.", jp:"明日、先生に連絡するつもりです。"},
  {pattern:"つもりです", en:"I plan to take my child to the zoo.", jp:"子供を動物園に連れていくつもりです。"},
  {pattern:"つもりです", en:"I plan to change the schedule.", jp:"予定を変えるつもりです。"},
  {pattern:"つもりです", en:"I plan to quit my job next month.", jp:"来月、仕事を辞めるつもりです。"},
  {pattern:"つもりです", en:"I plan to tidy my room this weekend.", jp:"週末に部屋を片付けるつもりです。"},
  {pattern:"つもりです", en:"I plan to leave the house at 9.", jp:"9時に家を出るつもりです。"},
  {pattern:"つもりです", en:"I plan to do laundry this weekend.", jp:"週末に洗濯するつもりです。"},
  {pattern:"つもりです", en:"I plan to serve as manager next year.", jp:"来年、部長を務めるつもりです。"},
  {pattern:"つもりです", en:"I plan to start going to the gym next month.", jp:"来月から、ジムに通うつもりです。"},
  {pattern:"つもりです", en:"I plan to apply next week.", jp:"来週、もうしこみするつもりです。"},

  // ~前に (dictionary form) — "before doing ~"
  {pattern:"前に", en:"Before eating, I wash my hands.", jp:"食べる前に、手を洗います。"},
  {pattern:"前に", en:"Before going out, I lock the door.", jp:"出かける前に、かぎをかけます。"},
  {pattern:"前に", en:"Before going home, I'll meet my friend.", jp:"帰る前に、友達に会います。"},
  {pattern:"前に", en:"Before cleaning, I open the windows.", jp:"掃除する前に、窓を開けます。"},
  {pattern:"前に", en:"Before going, I look at a map.", jp:"行く前に、地図を見ます。"},
  {pattern:"前に", en:"Before getting on the train, I buy a ticket.", jp:"電車に乗る前に、切符を買います。"},
  {pattern:"前に", en:"Before turning off the TV, I'll watch once more.", jp:"テレビを消す前に、もう一度見ます。"},
  {pattern:"前に", en:"Before climbing the mountain, I bring water.", jp:"山にのぼる前に、水を持っていきます。"},
  {pattern:"前に", en:"Before sleeping, I take a shower.", jp:"寝る前に、シャワーを浴びます。"},
  {pattern:"前に", en:"Before entering the room, I knock.", jp:"部屋に入る前に、ノックします。"},
  {pattern:"前に", en:"Before sleeping, I brush my teeth.", jp:"寝る前に、歯を磨きます。"},
  {pattern:"前に", en:"Before leaving the house, I turn off the lights.", jp:"家を出る前に、電気を消します。"},

  // ~ましょうか (ます stem) — "Shall we ~?"
  {pattern:"ましょうか", en:"Shall we watch a movie?", jp:"映画を見ましょうか。"},
  {pattern:"ましょうか", en:"Shall we eat lunch?", jp:"昼ご飯を食べましょうか。"},
  {pattern:"ましょうか", en:"Shall we go out?", jp:"出かけましょうか。"},
  {pattern:"ましょうか", en:"Shall we clean the room?", jp:"部屋を掃除しましょうか。"},
  {pattern:"ましょうか", en:"Shall we check the weather?", jp:"天気をチェックしましょうか。"},
  {pattern:"ましょうか", en:"Shall we wash the dishes?", jp:"お皿を洗いましょうか。"},
  {pattern:"ましょうか", en:"Shall we head home soon?", jp:"そろそろ帰りましょうか。"},
  {pattern:"ましょうか", en:"Shall I carry your bag?", jp:"かばんをもちましょうか。"},
  {pattern:"ましょうか", en:"Shall we decide where to go?", jp:"どこに行くか、きめましょうか。"},

  // plain ます form — polite present/future statement
  {pattern:"ます form", en:"I walk every day.", jp:"毎日、歩きます。"},
  {pattern:"ます form", en:"I will travel tomorrow.", jp:"明日、旅行します。"},
  {pattern:"ます form", en:"I do laundry on weekends.", jp:"週末に洗濯します。"},
  {pattern:"ます form", en:"I welcome my friend into my home.", jp:"友達を家に迎えます。"},
  {pattern:"ます form", en:"I go out on Saturdays.", jp:"土曜日に出かけます。"},

  // ~たいです (ます stem) — "I want to ~"
  {pattern:"たいです", en:"I want to go to Japan.", jp:"日本に行きたいです。"},
  {pattern:"たいです", en:"I want to buy a new car.", jp:"新しい車を買いたいです。"},
  {pattern:"たいです", en:"I want to memorize kanji.", jp:"漢字を覚えたいです。"},
  {pattern:"たいです", en:"I want to invite my friend.", jp:"友達を誘いたいです。"},
  {pattern:"たいです", en:"I want to drink coffee.", jp:"コーヒーを飲みたいです。"},
  {pattern:"たいです", en:"I want to help my friend.", jp:"友達を手伝いたいです。"},
  {pattern:"たいです", en:"I want to write a letter.", jp:"手紙を書きたいです。"},
  {pattern:"たいです", en:"I want to withdraw money.", jp:"お金をおろしたいです。"},
  {pattern:"たいです", en:"I want to ride the shinkansen.", jp:"新幹線に乗りたいです。"},
  {pattern:"たいです", en:"I want to climb the mountain.", jp:"山にのぼりたいです。"},
  {pattern:"たいです", en:"I want to pickle vegetables.", jp:"野菜を漬けたいです。"},
  {pattern:"たいです", en:"I want to use the computer.", jp:"パソコンを使いたいです。"},
  {pattern:"たいです", en:"I want to borrow a book.", jp:"本を借りたいです。"},
  {pattern:"たいです", en:"I want to ask the teacher.", jp:"先生にたずねたいです。"},
  {pattern:"たいです", en:"I want to change my hairstyle.", jp:"髪型を変えたいです。"},
  {pattern:"たいです", en:"I want to choose a present.", jp:"プレゼントを選びたいです。"},
  {pattern:"たいです", en:"I want to ask for help.", jp:"助けを頼みたいです。"},
  {pattern:"たいです", en:"I want to know the answer.", jp:"答えを知りたいです。"},
  {pattern:"たいです", en:"I want to order pizza.", jp:"ピザを注文したいです。"},
  {pattern:"たいです", en:"I want to do my homework.", jp:"宿題をやりたいです。"},

  // ~すぎました (ます stem) — "did too much of ~"
  {pattern:"すぎました", en:"I ate too much yesterday.", jp:"昨日、食べすぎました。"},
  {pattern:"すぎました", en:"I drank too much alcohol.", jp:"お酒を飲みすぎました。"},
  {pattern:"すぎました", en:"I walked too much today.", jp:"今日は歩きすぎました。"},
  {pattern:"すぎました", en:"I worked too much last night.", jp:"昨夜、働きすぎました。"},
  {pattern:"すぎました", en:"I bought too many clothes.", jp:"服を買いすぎました。"},
  {pattern:"すぎました", en:"I swam too much today.", jp:"今日は泳ぎすぎました。"},
  {pattern:"すぎました", en:"I cut my hair too much.", jp:"髪を切りすぎました。"},
  {pattern:"すぎました", en:"I hurried too much.", jp:"急ぎすぎました。"},
  {pattern:"すぎました", en:"I collected too many books.", jp:"本を集めすぎました。"},
  {pattern:"すぎました", en:"I added too much sugar.", jp:"砂糖を入れすぎました。"},
  {pattern:"すぎました", en:"I paid too much money.", jp:"お金を出しすぎました。"},

  // て form + ください — "please do ~"
  {pattern:"てください", en:"Please open the door.", jp:"ドアを開けてください。"},
  {pattern:"てください", en:"Please close the window.", jp:"窓を閉めてください。"},
  {pattern:"てください", en:"Please help me.", jp:"手伝ってください。"},
  {pattern:"てください", en:"Please sit here.", jp:"ここに座ってください。"},
  {pattern:"てください", en:"Please take this class.", jp:"このクラスをうけてください。"},
  {pattern:"てください", en:"Please check the email.", jp:"メールをチェックしてください。"},
  {pattern:"てください", en:"Please call later.", jp:"後で電話してください。"},
  {pattern:"てください", en:"Please wash your hands.", jp:"手を洗ってください。"},
  {pattern:"てください", en:"Please cut the paper.", jp:"紙を切ってください。"},
  {pattern:"てください", en:"Please turn on the light.", jp:"電気をつけてください。"},
  {pattern:"てください", en:"Please turn off the TV.", jp:"テレビを消してください。"},
  {pattern:"てください", en:"Please lend me a pen.", jp:"ペンを貸してください。"},
  {pattern:"てください", en:"Please hold the luggage.", jp:"荷物をもってください。"},
  {pattern:"てください", en:"Please pay here.", jp:"ここでお金を払ってください。"},
  {pattern:"てください", en:"Please put the sauce on.", jp:"ソースをかけてください。"},
  {pattern:"てください", en:"Please teach me Japanese.", jp:"日本語を教えてください。"},
  {pattern:"てください", en:"Please show me your passport.", jp:"パスポートを見せてください。"},
  {pattern:"てください", en:"Please hurry.", jp:"急いでください。"},
  {pattern:"てください", en:"Please contact me later.", jp:"後で連絡してください。"},
  {pattern:"てください", en:"Please say it again.", jp:"もう一度いってください。"},
  {pattern:"てください", en:"Please translate this sentence.", jp:"この文を訳してください。"},
  {pattern:"てください", en:"Please bring water.", jp:"お水を持ってきてください。"},
  {pattern:"てください", en:"Please bring your friend.", jp:"友達を連れてきてください。"},
  {pattern:"てください", en:"Please give me a ride in the car.", jp:"私を車に乗せてください。"},
  {pattern:"てください", en:"Please take an umbrella.", jp:"傘を持っていってください。"},
  {pattern:"てください", en:"Please move the desk.", jp:"机を動かしてください。"},
  {pattern:"てください", en:"Please add sugar.", jp:"砂糖を入れてください。"},
  {pattern:"てください", en:"Please tidy the room.", jp:"部屋を片付けてください。"},
  {pattern:"てください", en:"Please choose your favorite color.", jp:"好きな色を選んでください。"},
  {pattern:"てください", en:"Please pick me up at the station.", jp:"駅で迎えてください。"},
  {pattern:"てください", en:"Please submit your homework.", jp:"宿題を出してください。"},
  {pattern:"てください", en:"Please brush your teeth.", jp:"歯を磨いてください。"},
  {pattern:"てください", en:"Please memorize this word.", jp:"この単語を覚えてください。"},
  {pattern:"てください", en:"Please invite your friend.", jp:"友達を誘ってください。"},
  {pattern:"てください", en:"Please order coffee.", jp:"コーヒーを頼んでください。"},
  {pattern:"てください", en:"Please fix the computer.", jp:"パソコンをなおしてください。"},
  {pattern:"てください", en:"Please apply here.", jp:"ここでもうしこみしてください。"},
  {pattern:"てください", en:"Please decide the schedule.", jp:"予定をきめてください。"},
  {pattern:"てください", en:"Please do this.", jp:"これをやってください。"},
  {pattern:"てください", en:"Please order coffee (at a shop).", jp:"コーヒーを注文してください。"},

  // て form + いただけませんか — polite request "could you please ~"
  {pattern:"ていただけませんか", en:"Could you please help me?", jp:"手伝っていただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please open the window?", jp:"窓を開けていただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please say that again?", jp:"もう一度話していただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please lend it to me?", jp:"貸していただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please translate this?", jp:"これを訳していただけませんか。"},
  {pattern:"ていただけませんか", en:"Could you please fix the car?", jp:"車をなおしていただけませんか。"},

  // て form + もいいですか — "may I ~?"
  {pattern:"てもいいですか", en:"May I sit here?", jp:"ここに座ってもいいですか。"},
  {pattern:"てもいいですか", en:"May I use this?", jp:"これを使ってもいいですか。"},
  {pattern:"てもいいですか", en:"May I take a photo?", jp:"写真を撮ってもいいですか。"},
  {pattern:"てもいいですか", en:"May I turn on the TV?", jp:"テレビをつけてもいいですか。"},
  {pattern:"てもいいですか", en:"May I watch this video?", jp:"このビデオを見てもいいですか。"},
  {pattern:"てもいいですか", en:"May I close the window?", jp:"窓を閉めてもいいですか。"},
  {pattern:"てもいいですか", en:"May I ask a question?", jp:"質問を聞いてもいいですか。"},
  {pattern:"てもいいですか", en:"May I come in?", jp:"入ってもいいですか。"},
  {pattern:"てもいいですか", en:"May I borrow an umbrella?", jp:"傘を借りてもいいですか。"},
  {pattern:"てもいいですか", en:"May I ask a question? (formal)", jp:"質問をたずねてもいいですか。"},
  {pattern:"てもいいですか", en:"May I show you a photo?", jp:"写真を見せてもいいですか。"},
  {pattern:"てもいいですか", en:"May I smoke here?", jp:"ここでタバコをすってもいいですか。"},

  // て form + います — ongoing / habitual action
  {pattern:"ています", en:"I am cleaning now.", jp:"今、掃除しています。"},
  {pattern:"ています", en:"I work at a bank.", jp:"銀行で働いています。"},
  {pattern:"ています", en:"I am on the phone now.", jp:"今、電話しています。"},
  {pattern:"ています", en:"I walk in the park every morning.", jp:"毎朝、公園を歩いています。"},
  {pattern:"ています", en:"I am cooking dinner now.", jp:"今、晩ご飯をりょうりしています。"},
  {pattern:"ています", en:"I am making dinner now.", jp:"今、晩ご飯を作っています。"},
  {pattern:"ています", en:"I am writing a report now.", jp:"今、レポートを書いています。"},
  {pattern:"ています", en:"I am taking photos now.", jp:"今、写真を撮っています。"},
  {pattern:"ています", en:"I live in Tokyo.", jp:"東京にすんでいます。"},
  {pattern:"ています", en:"I am taking a shower now.", jp:"今、シャワーを浴びています。"},
  {pattern:"ています", en:"I am looking for a job now.", jp:"今、仕事を探しています。"},
  {pattern:"ています", en:"I am playing the guitar now.", jp:"今、ギターを弾いています。"},
  {pattern:"ています", en:"He serves as a teacher.", jp:"彼は先生を務めています。"},
  {pattern:"ています", en:"I commute to school every day.", jp:"毎日、学校に通っています。"},

  // て form + いました — past progressive
  {pattern:"ていました", en:"I was watching TV last night.", jp:"昨日の夜、テレビを見ていました。"},
  {pattern:"ていました", en:"I was cleaning my room at that time.", jp:"その時、部屋を掃除していました。"},
  {pattern:"ていました", en:"I used to swim a lot as a child.", jp:"子供の時、よく泳いでいました。"},
  {pattern:"ていました", en:"I was talking with her.", jp:"彼女と話していました。"},
  {pattern:"ていました", en:"The movie had already started.", jp:"映画はもう始まっていました。"},

  // まだ〜ていません — "haven't done ~ yet"
  {pattern:"まだ〜ていません", en:"I haven't cleaned yet.", jp:"まだ掃除していません。"},
  {pattern:"まだ〜ていません", en:"I haven't eaten yet.", jp:"まだ食べていません。"},
  {pattern:"まだ〜ていません", en:"I haven't graduated yet.", jp:"まだ卒業していません。"},
  {pattern:"まだ〜ていません", en:"I haven't gotten married yet.", jp:"まだ結婚していません。"},
  {pattern:"まだ〜ていません", en:"I haven't opened the door yet.", jp:"まだドアを開けていません。"},
  {pattern:"まだ〜ていません", en:"I haven't quit my job yet.", jp:"まだ仕事を辞めていません。"},
  {pattern:"まだ〜ていません", en:"We haven't broken up yet.", jp:"まだ別れていません。"},
  {pattern:"まだ〜ていません", en:"It hasn't started yet.", jp:"まだ始まっていません。"},
  {pattern:"まだ〜ていません", en:"This plant hasn't died yet.", jp:"この植物はまだ死んでいません。"},

  // て form as connector — "I'll do X, then Y"
  {pattern:"て (connector)", en:"I'll eat breakfast, then go to school.", jp:"朝ご飯を食べて、学校に行きます。"},
  {pattern:"て (connector)", en:"I'll wash my hands, then eat.", jp:"手を洗って、食べます。"},
  {pattern:"て (connector)", en:"I'll clean, then do laundry.", jp:"掃除して、洗濯します。"},
  {pattern:"て (connector)", en:"I'll call my friend, then go out.", jp:"友達に電話して、出かけます。"},
  {pattern:"て (connector)", en:"I'll go out, then come home late.", jp:"出かけて、遅く帰ります。"}
];
