// Verb Dojo vocab list — edit this file directly to add/change words.
// Each entry: dict = dictionary form, english = meaning, masu = ~ます form, te = ~て form,
// group = verb group (1 = Group 1/u-verb/godan, 2 = Group 2/ru-verb/ichidan, 3 = Group 3/irregular),
// hiragana = reading of the dict form (used for furigana). If a word has no kanji, hiragana matches dict.
// masuHiragana/teHiragana = reading of masu/te (accepted as correct alongside the kanji form in Typing mode).
// nai = plain negative (~ない) form. naiHiragana = its reading.
window.VOCAB_WORDS = [
  {dict:"食べる", english:"to eat", masu:"食べます", te:"食べて", group:2, hiragana:"たべる", masuHiragana:"たべます", teHiragana:"たべて", nai:"食べない", naiHiragana:"たべない"},
  {dict:"飲む", english:"to drink", masu:"飲みます", te:"飲んで", group:1, hiragana:"のむ", masuHiragana:"のみます", teHiragana:"のんで", nai:"飲まない", naiHiragana:"のまない"},
  {dict:"見る", english:"to see / watch", masu:"見ます", te:"見て", group:2, hiragana:"みる", masuHiragana:"みます", teHiragana:"みて", nai:"見ない", naiHiragana:"みない"},
  {dict:"行く", english:"to go", masu:"行きます", te:"行って", group:1, hiragana:"いく", masuHiragana:"いきます", teHiragana:"いって", nai:"行かない", naiHiragana:"いかない"},
  {dict:"話す", english:"to speak", masu:"話します", te:"話して", group:1, hiragana:"はなす", masuHiragana:"はなします", teHiragana:"はなして", nai:"話さない", naiHiragana:"はなさない"},
  {dict:"出かける", english:"to go out", masu:"出かけます", te:"出かけて", group:2, hiragana:"でかける", masuHiragana:"でかけます", teHiragana:"でかけて", nai:"出かけない", naiHiragana:"でかけない"},
  {dict:"うける", english:"to receive / to take (a class, a test)", masu:"うけます", te:"うけて", group:2, hiragana:"うける", masuHiragana:"うけます", teHiragana:"うけて", nai:"うけない", naiHiragana:"うけない"},
  {dict:"りょうりする", english:"to cook", masu:"りょうりします", te:"りょうりして", group:3, hiragana:"りょうりする", masuHiragana:"りょうりします", teHiragana:"りょうりして", nai:"りょうりしない", naiHiragana:"りょうりしない"},
  {dict:"電話する", english:"to make a phone call", masu:"電話します", te:"電話して", group:3, hiragana:"でんわする", masuHiragana:"でんわします", teHiragana:"でんわして", nai:"電話しない", naiHiragana:"でんわしない"},
  {dict:"チェックする", english:"to check", masu:"チェックします", te:"チェックして", group:3, hiragana:"チェックする", masuHiragana:"チェックします", teHiragana:"チェックして", nai:"チェックしない", naiHiragana:"チェックしない"},
  {dict:"買う", english:"to buy", masu:"買います", te:"買って", group:1, hiragana:"かう", masuHiragana:"かいます", teHiragana:"かって", nai:"買わない", naiHiragana:"かわない"},
  {dict:"あう", english:"to meet", masu:"あいます", te:"あって", group:1, hiragana:"あう", masuHiragana:"あいます", teHiragana:"あって", nai:"あわない", naiHiragana:"あわない"},
  {dict:"洗う", english:"to wash", masu:"洗います", te:"洗って", group:1, hiragana:"あらう", masuHiragana:"あらいます", teHiragana:"あらって", nai:"洗わない", naiHiragana:"あらわない"},
  {dict:"聞く", english:"to listen / to ask", masu:"聞きます", te:"聞いて", group:1, hiragana:"きく", masuHiragana:"ききます", teHiragana:"きいて", nai:"聞かない", naiHiragana:"きかない"},
  {dict:"書く", english:"to write", masu:"書きます", te:"書いて", group:1, hiragana:"かく", masuHiragana:"かきます", teHiragana:"かいて", nai:"書かない", naiHiragana:"かかない"},
  {dict:"泳ぐ", english:"to swim", masu:"泳ぎます", te:"泳いで", group:1, hiragana:"およぐ", masuHiragana:"およぎます", teHiragana:"およいで", nai:"泳がない", naiHiragana:"およがない"},
  {dict:"おろす", english:"to withdraw (money) / take down", masu:"おろします", te:"おろして", group:1, hiragana:"おろす", masuHiragana:"おろします", teHiragana:"おろして", nai:"おろさない", naiHiragana:"おろさない"},
  {dict:"帰る", english:"to go home / return", masu:"帰ります", te:"帰って", group:1, hiragana:"かえる", masuHiragana:"かえります", teHiragana:"かえって", nai:"帰らない", naiHiragana:"かえらない"},
  {dict:"乗る", english:"to ride / get on", masu:"乗ります", te:"乗って", group:1, hiragana:"のる", masuHiragana:"のります", teHiragana:"のって", nai:"乗らない", naiHiragana:"のらない"},
  {dict:"切る", english:"to cut", masu:"切ります", te:"切って", group:1, hiragana:"きる", masuHiragana:"きります", teHiragana:"きって", nai:"切らない", naiHiragana:"きらない"},
  {dict:"開ける", english:"to open (something)", masu:"開けます", te:"開けて", group:2, hiragana:"あける", masuHiragana:"あけます", teHiragana:"あけて", nai:"開けない", naiHiragana:"あけない"},
  {dict:"閉める", english:"to close (something)", masu:"閉めます", te:"閉めて", group:2, hiragana:"しめる", masuHiragana:"しめます", teHiragana:"しめて", nai:"閉めない", naiHiragana:"しめない"},
  {dict:"つける", english:"to turn on (a light, TV, etc.)", masu:"つけます", te:"つけて", group:2, hiragana:"つける", masuHiragana:"つけます", teHiragana:"つけて", nai:"つけない", naiHiragana:"つけない"},
  {dict:"手伝う", english:"to help", masu:"手伝います", te:"手伝って", group:1, hiragana:"てつだう", masuHiragana:"てつだいます", teHiragana:"てつだって", nai:"手伝わない", naiHiragana:"てつだわない"},
  {dict:"消す", english:"to turn off / to erase", masu:"消します", te:"消して", group:1, hiragana:"けす", masuHiragana:"けします", teHiragana:"けして", nai:"消さない", naiHiragana:"けさない"},
  {dict:"貸す", english:"to lend", masu:"貸します", te:"貸して", group:1, hiragana:"かす", masuHiragana:"かします", teHiragana:"かして", nai:"貸さない", naiHiragana:"かさない"},
  {dict:"もつ", english:"to hold / to carry", masu:"もちます", te:"もって", group:1, hiragana:"もつ", masuHiragana:"もちます", teHiragana:"もって", nai:"もたない", naiHiragana:"もたない"},
  {dict:"作る", english:"to make", masu:"作ります", te:"作って", group:1, hiragana:"つくる", masuHiragana:"つくります", teHiragana:"つくって", nai:"作らない", naiHiragana:"つくらない"},
  {dict:"旅行する", english:"to travel", masu:"旅行します", te:"旅行して", group:3, hiragana:"りょこうする", masuHiragana:"りょこうします", teHiragana:"りょこうして", nai:"旅行しない", naiHiragana:"りょこうしない"},
  {dict:"払う", english:"to pay", masu:"払います", te:"払って", group:1, hiragana:"はらう", masuHiragana:"はらいます", teHiragana:"はらって", nai:"払わない", naiHiragana:"はらわない"},
  {dict:"働く", english:"to work", masu:"働きます", te:"働いて", group:1, hiragana:"はたらく", masuHiragana:"はたらきます", teHiragana:"はたらいて", nai:"働かない", naiHiragana:"はたらかない"},
  {dict:"遊ぶ", english:"to play", masu:"遊びます", te:"遊んで", group:1, hiragana:"あそぶ", masuHiragana:"あそびます", teHiragana:"あそんで", nai:"遊ばない", naiHiragana:"あそばない"},
  {dict:"すむ", english:"to live / to reside", masu:"すみます", te:"すんで", group:1, hiragana:"すむ", masuHiragana:"すみます", teHiragana:"すんで", nai:"すまない", naiHiragana:"すまない"},
  {dict:"写真を撮る", english:"to take a photo", masu:"写真を撮ります", te:"写真を撮って", group:1, hiragana:"しゃしんをとる", masuHiragana:"しゃしんをとります", teHiragana:"しゃしんをとって", nai:"写真を撮らない", naiHiragana:"しゃしんをとらない"},
  {dict:"のぼる", english:"to climb", masu:"のぼります", te:"のぼって", group:1, hiragana:"のぼる", masuHiragana:"のぼります", teHiragana:"のぼって", nai:"のぼらない", naiHiragana:"のぼらない"},
  {dict:"漬ける", english:"to soak / to pickle", masu:"漬けます", te:"漬けて", group:2, hiragana:"つける", masuHiragana:"つけます", teHiragana:"つけて", nai:"漬けない", naiHiragana:"つけない"},
  {dict:"かける", english:"to put on (sauce, dressing)", masu:"かけます", te:"かけて", group:2, hiragana:"かける", masuHiragana:"かけます", teHiragana:"かけて", nai:"かけない", naiHiragana:"かけない"},
  {dict:"歩く", english:"to walk", masu:"歩きます", te:"歩いて", group:1, hiragana:"あるく", masuHiragana:"あるきます", teHiragana:"あるいて", nai:"歩かない", naiHiragana:"あるかない"},
  {dict:"使う", english:"to use", masu:"使います", te:"使って", group:1, hiragana:"つかう", masuHiragana:"つかいます", teHiragana:"つかって", nai:"使わない", naiHiragana:"つかわない"},
  {dict:"教える", english:"to teach", masu:"教えます", te:"教えて", group:2, hiragana:"おしえる", masuHiragana:"おしえます", teHiragana:"おしえて", nai:"教えない", naiHiragana:"おしえない"},
  {dict:"見せる", english:"to show", masu:"見せます", te:"見せて", group:2, hiragana:"みせる", masuHiragana:"みせます", teHiragana:"みせて", nai:"見せない", naiHiragana:"みせない"},
  {dict:"座る", english:"to sit", masu:"座ります", te:"座って", group:1, hiragana:"すわる", masuHiragana:"すわります", teHiragana:"すわって", nai:"座らない", naiHiragana:"すわらない"},
  {dict:"急ぐ", english:"to hurry", masu:"急ぎます", te:"急いで", group:1, hiragana:"いそぐ", masuHiragana:"いそぎます", teHiragana:"いそいで", nai:"急がない", naiHiragana:"いそがない"},
  {dict:"浴びる", english:"to bathe / to take a shower", masu:"浴びます", te:"浴びて", group:2, hiragana:"あびる", masuHiragana:"あびます", teHiragana:"あびて", nai:"浴びない", naiHiragana:"あびない"},
  {dict:"連絡する", english:"to contact", masu:"連絡します", te:"連絡して", group:3, hiragana:"れんらくする", masuHiragana:"れんらくします", teHiragana:"れんらくして", nai:"連絡しない", naiHiragana:"れんらくしない"},
  {dict:"いう", english:"to say", masu:"いいます", te:"いって", group:1, hiragana:"いう", masuHiragana:"いいます", teHiragana:"いって", nai:"いわない", naiHiragana:"いわない"},
  {dict:"探す", english:"to search / to look for", masu:"探します", te:"探して", group:1, hiragana:"さがす", masuHiragana:"さがします", teHiragana:"さがして", nai:"探さない", naiHiragana:"さがさない"},
  {dict:"訳す", english:"to translate", masu:"訳します", te:"訳して", group:1, hiragana:"やくす", masuHiragana:"やくします", teHiragana:"やくして", nai:"訳さない", naiHiragana:"やくさない"},
  {dict:"入る", english:"to enter", masu:"入ります", te:"入って", group:1, hiragana:"はいる", masuHiragana:"はいります", teHiragana:"はいって", nai:"入らない", naiHiragana:"はいらない"},
  {dict:"借りる", english:"to borrow", masu:"借ります", te:"借りて", group:2, hiragana:"かりる", masuHiragana:"かります", teHiragana:"かりて", nai:"借りない", naiHiragana:"かりない"},
  {dict:"持ってくる", english:"to bring (a thing)", masu:"持ってきます", te:"持ってきて", group:3, hiragana:"もってくる", masuHiragana:"もってきます", teHiragana:"もってきて", nai:"持ってこない", naiHiragana:"もってこない"},
  {dict:"連れてくる", english:"to bring (a person / animal)", masu:"連れてきます", te:"連れてきて", group:3, hiragana:"つれてくる", masuHiragana:"つれてきます", teHiragana:"つれてきて", nai:"連れてこない", naiHiragana:"つれてこない"},
  {dict:"タバコをすう", english:"to smoke (a cigarette)", masu:"タバコをすいます", te:"タバコをすって", group:1, hiragana:"タバコをすう", masuHiragana:"タバコをすいます", teHiragana:"タバコをすって", nai:"タバコをすわない", naiHiragana:"タバコをすわない"},
  {dict:"乗せる", english:"to put (an object) on", masu:"乗せます", te:"乗せて", group:2, hiragana:"のせる", masuHiragana:"のせます", teHiragana:"のせて", nai:"乗せない", naiHiragana:"のせない"},
  {dict:"たずねる", english:"to ask", masu:"たずねます", te:"たずねて", group:2, hiragana:"たずねる", masuHiragana:"たずねます", teHiragana:"たずねて", nai:"たずねない", naiHiragana:"たずねない"},
  {dict:"持っていく", english:"to take (things)", masu:"持っていきます", te:"持っていって", group:1, hiragana:"もっていく", masuHiragana:"もっていきます", teHiragana:"もっていって", nai:"持っていかない", naiHiragana:"もっていかない"},
  {dict:"連れていく", english:"to take (person / animal)", masu:"連れていきます", te:"連れていって", group:1, hiragana:"つれていく", masuHiragana:"つれていきます", teHiragana:"つれていって", nai:"連れていかない", naiHiragana:"つれていかない"},
  {dict:"変える", english:"to change (something)", masu:"変えます", te:"変えて", group:2, hiragana:"かえる", masuHiragana:"かえます", teHiragana:"かえて", nai:"変えない", naiHiragana:"かえない"},
  {dict:"弾く", english:"to play (a stringed instrument or piano)", masu:"弾きます", te:"弾いて", group:1, hiragana:"ひく", masuHiragana:"ひきます", teHiragana:"ひいて", nai:"弾かない", naiHiragana:"ひかない"},
  {dict:"集める", english:"to collect / to gather", masu:"集めます", te:"集めて", group:2, hiragana:"あつめる", masuHiragana:"あつめます", teHiragana:"あつめて", nai:"集めない", naiHiragana:"あつめない"},
  {dict:"動かす", english:"to move (something)", masu:"動かします", te:"動かして", group:1, hiragana:"うごかす", masuHiragana:"うごかします", teHiragana:"うごかして", nai:"動かさない", naiHiragana:"うごかさない"},
  {dict:"辞める", english:"to quit (a job)", masu:"辞めます", te:"辞めて", group:2, hiragana:"やめる", masuHiragana:"やめます", teHiragana:"やめて", nai:"辞めない", naiHiragana:"やめない"},
  {dict:"別れる", english:"to separate / to break up (with someone)", masu:"別れます", te:"別れて", group:2, hiragana:"わかれる", masuHiragana:"わかれます", teHiragana:"わかれて", nai:"別れない", naiHiragana:"わかれない"},
  {dict:"始まる", english:"to begin (intransitive)", masu:"始まります", te:"始まって", group:1, hiragana:"はじまる", masuHiragana:"はじまります", teHiragana:"はじまって", nai:"始まらない", naiHiragana:"はじまらない"},
  {dict:"死ぬ", english:"to die", masu:"死にます", te:"死んで", group:1, hiragana:"しぬ", masuHiragana:"しにます", teHiragana:"しんで", nai:"死なない", naiHiragana:"しなない"},
  {dict:"入れる", english:"to put in / to insert", masu:"入れます", te:"入れて", group:2, hiragana:"いれる", masuHiragana:"いれます", teHiragana:"いれて", nai:"入れない", naiHiragana:"いれない"},
  {dict:"片付ける", english:"to tidy up / to put away", masu:"片付けます", te:"片付けて", group:2, hiragana:"かたづける", masuHiragana:"かたづけます", teHiragana:"かたづけて", nai:"片付けない", naiHiragana:"かたづけない"},
  {dict:"選ぶ", english:"to choose / to select", masu:"選びます", te:"選んで", group:1, hiragana:"えらぶ", masuHiragana:"えらびます", teHiragana:"えらんで", nai:"選ばない", naiHiragana:"えらばない"},
  {dict:"迎える", english:"to welcome / to pick up (someone)", masu:"迎えます", te:"迎えて", group:2, hiragana:"むかえる", masuHiragana:"むかえます", teHiragana:"むかえて", nai:"迎えない", naiHiragana:"むかえない"},
  {dict:"出す", english:"to take out / to submit", masu:"出します", te:"出して", group:1, hiragana:"だす", masuHiragana:"だします", teHiragana:"だして", nai:"出さない", naiHiragana:"ださない"},
  {dict:"磨く", english:"to brush (teeth) / to polish", masu:"磨きます", te:"磨いて", group:1, hiragana:"みがく", masuHiragana:"みがきます", teHiragana:"みがいて", nai:"磨かない", naiHiragana:"みがかない"},
  {dict:"出る", english:"to leave / to exit / to attend", masu:"出ます", te:"出て", group:2, hiragana:"でる", masuHiragana:"でます", teHiragana:"でて", nai:"出ない", naiHiragana:"でない"},
  {dict:"卒業する", english:"to graduate", masu:"卒業します", te:"卒業して", group:3, hiragana:"そつぎょうする", masuHiragana:"そつぎょうします", teHiragana:"そつぎょうして", nai:"卒業しない", naiHiragana:"そつぎょうしない"},
  {dict:"結婚する", english:"to marry", masu:"結婚します", te:"結婚して", group:3, hiragana:"けっこんする", masuHiragana:"けっこんします", teHiragana:"けっこんして", nai:"結婚しない", naiHiragana:"けっこんしない"},
  {dict:"覚える", english:"to remember / to memorize", masu:"覚えます", te:"覚えて", group:2, hiragana:"おぼえる", masuHiragana:"おぼえます", teHiragana:"おぼえて", nai:"覚えない", naiHiragana:"おぼえない"},
  {dict:"掃除する", english:"to clean", masu:"掃除します", te:"掃除して", group:3, hiragana:"そうじする", masuHiragana:"そうじします", teHiragana:"そうじして", nai:"掃除しない", naiHiragana:"そうじしない"},
  {dict:"洗濯する", english:"to do laundry", masu:"洗濯します", te:"洗濯して", group:3, hiragana:"せんたくする", masuHiragana:"せんたくします", teHiragana:"せんたくして", nai:"洗濯しない", naiHiragana:"せんたくしない"},
  {dict:"誘う", english:"to invite", masu:"誘います", te:"誘って", group:1, hiragana:"さそう", masuHiragana:"さそいます", teHiragana:"さそって", nai:"誘わない", naiHiragana:"さそわない"},
  {dict:"頼む", english:"to ask / to request", masu:"頼みます", te:"頼んで", group:1, hiragana:"たのむ", masuHiragana:"たのみます", teHiragana:"たのんで", nai:"頼まない", naiHiragana:"たのまない"},
  {dict:"務める", english:"to serve (in a role) / to hold a post", masu:"務めます", te:"務めて", group:2, hiragana:"つとめる", masuHiragana:"つとめます", teHiragana:"つとめて", nai:"務めない", naiHiragana:"つとめない"},
  {dict:"通う", english:"to commute / to attend regularly", masu:"通います", te:"通って", group:1, hiragana:"かよう", masuHiragana:"かよいます", teHiragana:"かよって", nai:"通わない", naiHiragana:"かよわない"},
  {dict:"知る", english:"to know / to get to know", masu:"知ります", te:"知って", group:1, hiragana:"しる", masuHiragana:"しります", teHiragana:"しって", nai:"知らない", naiHiragana:"しらない"},
  {dict:"注文する", english:"to order (food, a product)", masu:"注文します", te:"注文して", group:3, hiragana:"ちゅうもんする", masuHiragana:"ちゅうもんします", teHiragana:"ちゅうもんして", nai:"注文しない", naiHiragana:"ちゅうもんしない"},
  {dict:"なおす", english:"to fix / to repair", masu:"なおします", te:"なおして", group:1, hiragana:"なおす", masuHiragana:"なおします", teHiragana:"なおして", nai:"なおさない", naiHiragana:"なおさない"},
  {dict:"もうしこみする", english:"to apply (for something)", masu:"もうしこみします", te:"もうしこみして", group:3, hiragana:"もうしこみする", masuHiragana:"もうしこみします", teHiragana:"もうしこみして", nai:"もうしこみしない", naiHiragana:"もうしこみしない"},
  {dict:"きめる", english:"to decide", masu:"きめます", te:"きめて", group:2, hiragana:"きめる", masuHiragana:"きめます", teHiragana:"きめて", nai:"きめない", naiHiragana:"きめない"},
  {dict:"やる", english:"to do (casual)", masu:"やります", te:"やって", group:1, hiragana:"やる", masuHiragana:"やります", teHiragana:"やって", nai:"やらない", naiHiragana:"やらない"},
  {dict:"忘れる", english:"to forget", masu:"忘れます", te:"忘れて", group:2, hiragana:"わすれる", masuHiragana:"わすれます", teHiragana:"わすれて", nai:"忘れない", naiHiragana:"わすれない"},
  {dict:"運転する", english:"to drive", masu:"運転します", te:"運転して", group:3, hiragana:"うんてんする", masuHiragana:"うんてんします", teHiragana:"うんてんして", nai:"運転しない", naiHiragana:"うんてんしない"},
  {dict:"習う", english:"to learn / to study (under someone)", masu:"習います", te:"習って", group:1, hiragana:"ならう", masuHiragana:"ならいます", teHiragana:"ならって", nai:"習わない", naiHiragana:"ならわない"},
  {dict:"道に迷う", english:"to get lost", masu:"道に迷います", te:"道に迷って", group:1, hiragana:"みちにまよう", masuHiragana:"みちにまよいます", teHiragana:"みちにまよって", nai:"道に迷わない", naiHiragana:"みちにまよわない"},
  {dict:"休む", english:"to rest / to take a day off", masu:"休みます", te:"休んで", group:1, hiragana:"やすむ", masuHiragana:"やすみます", teHiragana:"やすんで", nai:"休まない", naiHiragana:"やすまない"},
  {dict:"泊まる", english:"to stay overnight / to lodge", masu:"泊まります", te:"泊まって", group:1, hiragana:"とまる", masuHiragana:"とまります", teHiragana:"とまって", nai:"泊まらない", naiHiragana:"とまらない"},
  {dict:"サボる", english:"to skip / to cut (class, work)", masu:"サボります", te:"サボって", group:1, hiragana:"サボる", masuHiragana:"サボります", teHiragana:"サボって", nai:"サボらない", naiHiragana:"サボらない"},
  {dict:"やめる", english:"to quit / to give up (a habit, activity)", masu:"やめます", te:"やめて", group:2, hiragana:"やめる", masuHiragana:"やめます", teHiragana:"やめて", nai:"やめない", naiHiragana:"やめない"},
  {dict:"調べる", english:"to look up / to investigate", masu:"調べます", te:"調べて", group:2, hiragana:"しらべる", masuHiragana:"しらべます", teHiragana:"しらべて", nai:"調べない", naiHiragana:"しらべない"},
  {dict:"散歩する", english:"to take a walk / to stroll", masu:"散歩します", te:"散歩して", group:3, hiragana:"さんぽする", masuHiragana:"さんぽします", teHiragana:"さんぽして", nai:"散歩しない", naiHiragana:"さんぽしない"},
  {dict:"ぶらぶらする", english:"to wander around / to stroll aimlessly", masu:"ぶらぶらします", te:"ぶらぶらして", group:3, hiragana:"ぶらぶらする", masuHiragana:"ぶらぶらします", teHiragana:"ぶらぶらして", nai:"ぶらぶらしない", naiHiragana:"ぶらぶらしない"},
  {dict:"準備する", english:"to prepare", masu:"準備します", te:"準備して", group:3, hiragana:"じゅんびする", masuHiragana:"じゅんびします", teHiragana:"じゅんびして", nai:"準備しない", naiHiragana:"じゅんびしない"},
  {dict:"相談する", english:"to consult / to discuss (a problem)", masu:"相談します", te:"相談して", group:3, hiragana:"そうだんする", masuHiragana:"そうだんします", teHiragana:"そうだんして", nai:"相談しない", naiHiragana:"そうだんしない"},
  {dict:"謝る", english:"to apologize", masu:"謝ります", te:"謝って", group:1, hiragana:"あやまる", masuHiragana:"あやまります", teHiragana:"あやまって", nai:"謝らない", naiHiragana:"あやまらない"},
  {dict:"遅れる", english:"to be late / to be delayed", masu:"遅れます", te:"遅れて", group:2, hiragana:"おくれる", masuHiragana:"おくれます", teHiragana:"おくれて", nai:"遅れない", naiHiragana:"おくれない"},
  {dict:"約束を忘れる", english:"to forget a promise / appointment", masu:"約束を忘れます", te:"約束を忘れて", group:2, hiragana:"やくそくをわすれる", masuHiragana:"やくそくをわすれます", teHiragana:"やくそくをわすれて", nai:"約束を忘れない", naiHiragana:"やくそくをわすれない"},
  {dict:"捨てる", english:"to throw away / to discard", masu:"捨てます", te:"捨てて", group:2, hiragana:"すてる", masuHiragana:"すてます", teHiragana:"すてて", nai:"捨てない", naiHiragana:"すてない"},
  {dict:"無理する", english:"to overdo it / to push oneself too hard", masu:"無理します", te:"無理して", group:3, hiragana:"むりする", masuHiragana:"むりします", teHiragana:"むりして", nai:"無理しない", naiHiragana:"むりしない"},
  {dict:"気にする", english:"to worry about / to mind (something)", masu:"気にします", te:"気にして", group:3, hiragana:"きにする", masuHiragana:"きにします", teHiragana:"きにして", nai:"気にしない", naiHiragana:"きにしない"},
  {dict:"心配する", english:"to worry / to be anxious", masu:"心配します", te:"心配して", group:3, hiragana:"しんぱいする", masuHiragana:"しんぱいします", teHiragana:"しんぱいして", nai:"心配しない", naiHiragana:"しんぱいしない"},
  {dict:"たつ", english:"to stand", masu:"たちます", te:"たって", group:1, hiragana:"たつ", masuHiragana:"たちます", teHiragana:"たって", nai:"たたない", naiHiragana:"たたない"}
];
