// Verb Dojo vocab list — edit this file directly to add/change words.
// Each entry: dict = dictionary form, english = meaning, masu = ~ます form, te = ~て form,
// group = verb group (1 = Group 1/u-verb/godan, 2 = Group 2/ru-verb/ichidan, 3 = Group 3/irregular),
// hiragana = reading of the dict form (used for furigana). If a word has no kanji, hiragana matches dict.
// masuHiragana/teHiragana = reading of masu/te (accepted as correct alongside the kanji form in Typing mode).
window.VOCAB_WORDS = [
  {dict:"食べる", english:"to eat", masu:"食べます", te:"食べて", group:2, hiragana:"たべる", masuHiragana:"たべます", teHiragana:"たべて"},
  {dict:"飲む", english:"to drink", masu:"飲みます", te:"飲んで", group:1, hiragana:"のむ", masuHiragana:"のみます", teHiragana:"のんで"},
  {dict:"見る", english:"to see / watch", masu:"見ます", te:"見て", group:2, hiragana:"みる", masuHiragana:"みます", teHiragana:"みて"},
  {dict:"行く", english:"to go", masu:"行きます", te:"行って", group:1, hiragana:"いく", masuHiragana:"いきます", teHiragana:"いって"},
  {dict:"話す", english:"to speak", masu:"話します", te:"話して", group:1, hiragana:"はなす", masuHiragana:"はなします", teHiragana:"はなして"},
  {dict:"出かける", english:"to go out", masu:"出かけます", te:"出かけて", group:2, hiragana:"でかける", masuHiragana:"でかけます", teHiragana:"でかけて"},
  {dict:"うける", english:"to receive / to take (a class, a test)", masu:"うけます", te:"うけて", group:2, hiragana:"うける", masuHiragana:"うけます", teHiragana:"うけて"},
  {dict:"りょうりする", english:"to cook", masu:"りょうりします", te:"りょうりして", group:3, hiragana:"りょうりする", masuHiragana:"りょうりします", teHiragana:"りょうりして"},
  {dict:"電話する", english:"to make a phone call", masu:"電話します", te:"電話して", group:3, hiragana:"でんわする", masuHiragana:"でんわします", teHiragana:"でんわして"},
  {dict:"チェックする", english:"to check", masu:"チェックします", te:"チェックして", group:3, hiragana:"チェックする", masuHiragana:"チェックします", teHiragana:"チェックして"},
  {dict:"買う", english:"to buy", masu:"買います", te:"買って", group:1, hiragana:"かう", masuHiragana:"かいます", teHiragana:"かって"},
  {dict:"あう", english:"to meet", masu:"あいます", te:"あって", group:1, hiragana:"あう", masuHiragana:"あいます", teHiragana:"あって"},
  {dict:"洗う", english:"to wash", masu:"洗います", te:"洗って", group:1, hiragana:"あらう", masuHiragana:"あらいます", teHiragana:"あらって"},
  {dict:"聞く", english:"to listen / to ask", masu:"聞きます", te:"聞いて", group:1, hiragana:"きく", masuHiragana:"ききます", teHiragana:"きいて"},
  {dict:"書く", english:"to write", masu:"書きます", te:"書いて", group:1, hiragana:"かく", masuHiragana:"かきます", teHiragana:"かいて"},
  {dict:"泳ぐ", english:"to swim", masu:"泳ぎます", te:"泳いで", group:1, hiragana:"およぐ", masuHiragana:"およぎます", teHiragana:"およいで"},
  {dict:"おろす", english:"to withdraw (money) / take down", masu:"おろします", te:"おろして", group:1, hiragana:"おろす", masuHiragana:"おろします", teHiragana:"おろして"},
  {dict:"帰る", english:"to go home / return", masu:"帰ります", te:"帰って", group:1, hiragana:"かえる", masuHiragana:"かえります", teHiragana:"かえって"},
  {dict:"乗る", english:"to ride / get on", masu:"乗ります", te:"乗って", group:1, hiragana:"のる", masuHiragana:"のります", teHiragana:"のって"},
  {dict:"切る", english:"to cut", masu:"切ります", te:"切って", group:1, hiragana:"きる", masuHiragana:"きります", teHiragana:"きって"},
  {dict:"開ける", english:"to open (something)", masu:"開けます", te:"開けて", group:2, hiragana:"あける", masuHiragana:"あけます", teHiragana:"あけて"},
  {dict:"閉める", english:"to close (something)", masu:"閉めます", te:"閉めて", group:2, hiragana:"しめる", masuHiragana:"しめます", teHiragana:"しめて"},
  {dict:"つける", english:"to turn on (a light, TV, etc.)", masu:"つけます", te:"つけて", group:2, hiragana:"つける", masuHiragana:"つけます", teHiragana:"つけて"},
  {dict:"手伝う", english:"to help", masu:"手伝います", te:"手伝って", group:1, hiragana:"てつだう", masuHiragana:"てつだいます", teHiragana:"てつだって"},
  {dict:"消す", english:"to turn off / to erase", masu:"消します", te:"消して", group:1, hiragana:"けす", masuHiragana:"けします", teHiragana:"けして"},
  {dict:"貸す", english:"to lend", masu:"貸します", te:"貸して", group:1, hiragana:"かす", masuHiragana:"かします", teHiragana:"かして"},
  {dict:"もつ", english:"to hold / to carry", masu:"もちます", te:"もって", group:1, hiragana:"もつ", masuHiragana:"もちます", teHiragana:"もって"},
  {dict:"作る", english:"to make", masu:"作ります", te:"作って", group:1, hiragana:"つくる", masuHiragana:"つくります", teHiragana:"つくって"},
  {dict:"旅行する", english:"to travel", masu:"旅行します", te:"旅行して", group:3, hiragana:"りょこうする", masuHiragana:"りょこうします", teHiragana:"りょこうして"},
  {dict:"払う", english:"to pay", masu:"払います", te:"払って", group:1, hiragana:"はらう", masuHiragana:"はらいます", teHiragana:"はらって"},
  {dict:"働く", english:"to work", masu:"働きます", te:"働いて", group:1, hiragana:"はたらく", masuHiragana:"はたらきます", teHiragana:"はたらいて"},
  {dict:"遊ぶ", english:"to play", masu:"遊びます", te:"遊んで", group:1, hiragana:"あそぶ", masuHiragana:"あそびます", teHiragana:"あそんで"},
  {dict:"すむ", english:"to live / to reside", masu:"すみます", te:"すんで", group:1, hiragana:"すむ", masuHiragana:"すみます", teHiragana:"すんで"},
  {dict:"写真を撮る", english:"to take a photo", masu:"写真を撮ります", te:"写真を撮って", group:1, hiragana:"しゃしんをとる", masuHiragana:"しゃしんをとります", teHiragana:"しゃしんをとって"},
  {dict:"のぼる", english:"to climb", masu:"のぼります", te:"のぼって", group:1, hiragana:"のぼる", masuHiragana:"のぼります", teHiragana:"のぼって"},
  {dict:"漬ける", english:"to soak / to pickle", masu:"漬けます", te:"漬けて", group:2, hiragana:"つける", masuHiragana:"つけます", teHiragana:"つけて"},
  {dict:"かける", english:"to put on (sauce, dressing)", masu:"かけます", te:"かけて", group:2, hiragana:"かける", masuHiragana:"かけます", teHiragana:"かけて"},
  {dict:"歩く", english:"to walk", masu:"歩きます", te:"歩いて", group:1, hiragana:"あるく", masuHiragana:"あるきます", teHiragana:"あるいて"},
  {dict:"使う", english:"to use", masu:"使います", te:"使って", group:1, hiragana:"つかう", masuHiragana:"つかいます", teHiragana:"つかって"},
  {dict:"教える", english:"to teach", masu:"教えます", te:"教えて", group:2, hiragana:"おしえる", masuHiragana:"おしえます", teHiragana:"おしえて"},
  {dict:"見せる", english:"to show", masu:"見せます", te:"見せて", group:2, hiragana:"みせる", masuHiragana:"みせます", teHiragana:"みせて"},
  {dict:"座る", english:"to sit", masu:"座ります", te:"座って", group:1, hiragana:"すわる", masuHiragana:"すわります", teHiragana:"すわって"},
  {dict:"急ぐ", english:"to hurry", masu:"急ぎます", te:"急いで", group:1, hiragana:"いそぐ", masuHiragana:"いそぎます", teHiragana:"いそいで"},
  {dict:"浴びる", english:"to bathe / to take a shower", masu:"浴びます", te:"浴びて", group:2, hiragana:"あびる", masuHiragana:"あびます", teHiragana:"あびて"},
  {dict:"連絡する", english:"to contact", masu:"連絡します", te:"連絡して", group:3, hiragana:"れんらくする", masuHiragana:"れんらくします", teHiragana:"れんらくして"},
  {dict:"いう", english:"to say", masu:"いいます", te:"いって", group:1, hiragana:"いう", masuHiragana:"いいます", teHiragana:"いって"},
  {dict:"探す", english:"to search / to look for", masu:"探します", te:"探して", group:1, hiragana:"さがす", masuHiragana:"さがします", teHiragana:"さがして"},
  {dict:"訳す", english:"to translate", masu:"訳します", te:"訳して", group:1, hiragana:"やくす", masuHiragana:"やくします", teHiragana:"やくして"},
  {dict:"入る", english:"to enter", masu:"入ります", te:"入って", group:1, hiragana:"はいる", masuHiragana:"はいります", teHiragana:"はいって"},
  {dict:"借りる", english:"to borrow", masu:"借ります", te:"借りて", group:2, hiragana:"かりる", masuHiragana:"かります", teHiragana:"かりて"},
  {dict:"持ってくる", english:"to bring (a thing)", masu:"持ってきます", te:"持ってきて", group:3, hiragana:"もってくる", masuHiragana:"もってきます", teHiragana:"もってきて"},
  {dict:"連れてくる", english:"to bring (a person / animal)", masu:"連れてきます", te:"連れてきて", group:3, hiragana:"つれてくる", masuHiragana:"つれてきます", teHiragana:"つれてきて"},
  {dict:"タバコをすう", english:"to smoke (a cigarette)", masu:"タバコをすいます", te:"タバコをすって", group:1, hiragana:"タバコをすう", masuHiragana:"タバコをすいます", teHiragana:"タバコをすって"},
  {dict:"乗せる", english:"to put (an object) on", masu:"乗せます", te:"乗せて", group:2, hiragana:"のせる", masuHiragana:"のせます", teHiragana:"のせて"},
  {dict:"たずねる", english:"to ask", masu:"たずねます", te:"たずねて", group:2, hiragana:"たずねる", masuHiragana:"たずねます", teHiragana:"たずねて"},
  {dict:"持っていく", english:"to take (things)", masu:"持っていきます", te:"持っていって", group:1, hiragana:"もっていく", masuHiragana:"もっていきます", teHiragana:"もっていって"},
  {dict:"連れていく", english:"to take (person / animal)", masu:"連れていきます", te:"連れていって", group:1, hiragana:"つれていく", masuHiragana:"つれていきます", teHiragana:"つれていって"},
  {dict:"変える", english:"to change (something)", masu:"変えます", te:"変えて", group:2, hiragana:"かえる", masuHiragana:"かえます", teHiragana:"かえて"},
  {dict:"弾く", english:"to play (a stringed instrument or piano)", masu:"弾きます", te:"弾いて", group:1, hiragana:"ひく", masuHiragana:"ひきます", teHiragana:"ひいて"},
  {dict:"集める", english:"to collect / to gather", masu:"集めます", te:"集めて", group:2, hiragana:"あつめる", masuHiragana:"あつめます", teHiragana:"あつめて"},
  {dict:"動かす", english:"to move (something)", masu:"動かします", te:"動かして", group:1, hiragana:"うごかす", masuHiragana:"うごかします", teHiragana:"うごかして"},
  {dict:"辞める", english:"to quit (a job)", masu:"辞めます", te:"辞めて", group:2, hiragana:"やめる", masuHiragana:"やめます", teHiragana:"やめて"},
  {dict:"別れる", english:"to separate / to break up (with someone)", masu:"別れます", te:"別れて", group:2, hiragana:"わかれる", masuHiragana:"わかれます", teHiragana:"わかれて"},
  {dict:"始まる", english:"to begin (intransitive)", masu:"始まります", te:"始まって", group:1, hiragana:"はじまる", masuHiragana:"はじまります", teHiragana:"はじまって"},
  {dict:"死ぬ", english:"to die", masu:"死にます", te:"死んで", group:1, hiragana:"しぬ", masuHiragana:"しにます", teHiragana:"しんで"},
  {dict:"入れる", english:"to put in / to insert", masu:"入れます", te:"入れて", group:2, hiragana:"いれる", masuHiragana:"いれます", teHiragana:"いれて"},
  {dict:"片付ける", english:"to tidy up / to put away", masu:"片付けます", te:"片付けて", group:2, hiragana:"かたづける", masuHiragana:"かたづけます", teHiragana:"かたづけて"},
  {dict:"選ぶ", english:"to choose / to select", masu:"選びます", te:"選んで", group:1, hiragana:"えらぶ", masuHiragana:"えらびます", teHiragana:"えらんで"},
  {dict:"迎える", english:"to welcome / to pick up (someone)", masu:"迎えます", te:"迎えて", group:2, hiragana:"むかえる", masuHiragana:"むかえます", teHiragana:"むかえて"},
  {dict:"出す", english:"to take out / to submit", masu:"出します", te:"出して", group:1, hiragana:"だす", masuHiragana:"だします", teHiragana:"だして"},
  {dict:"磨く", english:"to brush (teeth) / to polish", masu:"磨きます", te:"磨いて", group:1, hiragana:"みがく", masuHiragana:"みがきます", teHiragana:"みがいて"},
  {dict:"出る", english:"to leave / to exit / to attend", masu:"出ます", te:"出て", group:2, hiragana:"でる", masuHiragana:"でます", teHiragana:"でて"},
  {dict:"卒業する", english:"to graduate", masu:"卒業します", te:"卒業して", group:3, hiragana:"そつぎょうする", masuHiragana:"そつぎょうします", teHiragana:"そつぎょうして"},
  {dict:"結婚する", english:"to marry", masu:"結婚します", te:"結婚して", group:3, hiragana:"けっこんする", masuHiragana:"けっこんします", teHiragana:"けっこんして"},
  {dict:"覚える", english:"to remember / to memorize", masu:"覚えます", te:"覚えて", group:2, hiragana:"おぼえる", masuHiragana:"おぼえます", teHiragana:"おぼえて"},
  {dict:"掃除する", english:"to clean", masu:"掃除します", te:"掃除して", group:3, hiragana:"そうじする", masuHiragana:"そうじします", teHiragana:"そうじして"},
  {dict:"洗濯する", english:"to do laundry", masu:"洗濯します", te:"洗濯して", group:3, hiragana:"せんたくする", masuHiragana:"せんたくします", teHiragana:"せんたくして"},
  {dict:"誘う", english:"to invite", masu:"誘います", te:"誘って", group:1, hiragana:"さそう", masuHiragana:"さそいます", teHiragana:"さそって"},
  {dict:"頼む", english:"to ask / to request", masu:"頼みます", te:"頼んで", group:1, hiragana:"たのむ", masuHiragana:"たのみます", teHiragana:"たのんで"},
  {dict:"務める", english:"to serve (in a role) / to hold a post", masu:"務めます", te:"務めて", group:2, hiragana:"つとめる", masuHiragana:"つとめます", teHiragana:"つとめて"},
  {dict:"通う", english:"to commute / to attend regularly", masu:"通います", te:"通って", group:1, hiragana:"かよう", masuHiragana:"かよいます", teHiragana:"かよって"},
  {dict:"知る", english:"to know / to get to know", masu:"知ります", te:"知って", group:1, hiragana:"しる", masuHiragana:"しります", teHiragana:"しって"},
  {dict:"注文する", english:"to order (food, a product)", masu:"注文します", te:"注文して", group:3, hiragana:"ちゅうもんする", masuHiragana:"ちゅうもんします", teHiragana:"ちゅうもんして"},
  {dict:"なおす", english:"to fix / to repair", masu:"なおします", te:"なおして", group:1, hiragana:"なおす", masuHiragana:"なおします", teHiragana:"なおして"},
  {dict:"もうしこみする", english:"to apply (for something)", masu:"もうしこみします", te:"もうしこみして", group:3, hiragana:"もうしこみする", masuHiragana:"もうしこみします", teHiragana:"もうしこみして"},
  {dict:"きめる", english:"to decide", masu:"きめます", te:"きめて", group:2, hiragana:"きめる", masuHiragana:"きめます", teHiragana:"きめて"},
  {dict:"やる", english:"to do (casual)", masu:"やります", te:"やって", group:1, hiragana:"やる", masuHiragana:"やります", teHiragana:"やって"},
  {dict:"忘れる", english:"to forget", masu:"忘れます", te:"忘れて", group:2, hiragana:"わすれる", masuHiragana:"わすれます", teHiragana:"わすれて"},
  {dict:"運転する", english:"to drive", masu:"運転します", te:"運転して", group:3, hiragana:"うんてんする", masuHiragana:"うんてんします", teHiragana:"うんてんして"},
  {dict:"習う", english:"to learn / to study (under someone)", masu:"習います", te:"習って", group:1, hiragana:"ならう", masuHiragana:"ならいます", teHiragana:"ならって"},
  {dict:"道に迷う", english:"to get lost", masu:"道に迷います", te:"道に迷って", group:1, hiragana:"みちにまよう", masuHiragana:"みちにまよいます", teHiragana:"みちにまよって"},
  {dict:"休む", english:"to rest / to take a day off", masu:"休みます", te:"休んで", group:1, hiragana:"やすむ", masuHiragana:"やすみます", teHiragana:"やすんで"},
  {dict:"泊まる", english:"to stay overnight / to lodge", masu:"泊まります", te:"泊まって", group:1, hiragana:"とまる", masuHiragana:"とまります", teHiragana:"とまって"},
  {dict:"サボる", english:"to skip / to cut (class, work)", masu:"サボります", te:"サボって", group:1, hiragana:"サボる", masuHiragana:"サボります", teHiragana:"サボって"},
  {dict:"やめる", english:"to quit / to give up (a habit, activity)", masu:"やめます", te:"やめて", group:2, hiragana:"やめる", masuHiragana:"やめます", teHiragana:"やめて"},
  {dict:"調べる", english:"to look up / to investigate", masu:"調べます", te:"調べて", group:2, hiragana:"しらべる", masuHiragana:"しらべます", teHiragana:"しらべて"},
  {dict:"散歩する", english:"to take a walk / to stroll", masu:"散歩します", te:"散歩して", group:3, hiragana:"さんぽする", masuHiragana:"さんぽします", teHiragana:"さんぽして"},
  {dict:"ぶらぶらする", english:"to wander around / to stroll aimlessly", masu:"ぶらぶらします", te:"ぶらぶらして", group:3, hiragana:"ぶらぶらする", masuHiragana:"ぶらぶらします", teHiragana:"ぶらぶらして"},
  {dict:"準備する", english:"to prepare", masu:"準備します", te:"準備して", group:3, hiragana:"じゅんびする", masuHiragana:"じゅんびします", teHiragana:"じゅんびして"},
  {dict:"相談する", english:"to consult / to discuss (a problem)", masu:"相談します", te:"相談して", group:3, hiragana:"そうだんする", masuHiragana:"そうだんします", teHiragana:"そうだんして"},
  {dict:"謝る", english:"to apologize", masu:"謝ります", te:"謝って", group:1, hiragana:"あやまる", masuHiragana:"あやまります", teHiragana:"あやまって"}
];
