// Verb Dojo vocab list — edit this file directly to add/change words.
// Each entry: dict = dictionary form, english = meaning, masu = ~ます form, te = ~て form,
// group = verb group (1 = Group 1/u-verb/godan, 2 = Group 2/ru-verb/ichidan, 3 = Group 3/irregular).
window.VOCAB_WORDS = [
  {dict:"食べる", english:"to eat", masu:"食べます", te:"食べて", group:2},
  {dict:"飲む", english:"to drink", masu:"飲みます", te:"飲んで", group:1},
  {dict:"見る", english:"to see / watch", masu:"見ます", te:"見て", group:2},
  {dict:"行く", english:"to go", masu:"行きます", te:"行って", group:1},
  {dict:"話す", english:"to speak", masu:"話します", te:"話して", group:1},
  {dict:"出かける", english:"to go out", masu:"出かけます", te:"出かけて", group:2},
  {dict:"うける", english:"to receive / to take (a class, a test)", masu:"うけます", te:"うけて", group:2},
  {dict:"りょうりする", english:"to cook", masu:"りょうりします", te:"りょうりして", group:3},
  {dict:"電話する", english:"to make a phone call", masu:"電話します", te:"電話して", group:3},
  {dict:"チェックする", english:"to check", masu:"チェックします", te:"チェックして", group:3},
  {dict:"買う", english:"to buy", masu:"買います", te:"買って", group:1},
  {dict:"あう", english:"to meet", masu:"あいます", te:"あって", group:1},
  {dict:"洗う", english:"to wash", masu:"洗います", te:"洗って", group:1},
  {dict:"聞く", english:"to listen / to ask", masu:"聞きます", te:"聞いて", group:1},
  {dict:"書く", english:"to write", masu:"書きます", te:"書いて", group:1},
  {dict:"泳ぐ", english:"to swim", masu:"泳ぎます", te:"泳いで", group:1},
  {dict:"おろす", english:"to withdraw (money) / take down", masu:"おろします", te:"おろして", group:1},
  {dict:"帰る", english:"to go home / return", masu:"帰ります", te:"帰って", group:1},
  {dict:"乗る", english:"to ride / get on", masu:"乗ります", te:"乗って", group:1},
  {dict:"切る", english:"to cut", masu:"切ります", te:"切って", group:1},
  {dict:"開ける", english:"to open (something)", masu:"開けます", te:"開けて", group:2},
  {dict:"閉める", english:"to close (something)", masu:"閉めます", te:"閉めて", group:2},
  {dict:"つける", english:"to turn on (a light, TV, etc.)", masu:"つけます", te:"つけて", group:2},
  {dict:"手伝う", english:"to help", masu:"手伝います", te:"手伝って", group:1},
  {dict:"消す", english:"to turn off / to erase", masu:"消します", te:"消して", group:1},
  {dict:"貸す", english:"to lend", masu:"貸します", te:"貸して", group:1},
  {dict:"もつ", english:"to hold / to carry", masu:"もちます", te:"もって", group:1},
  {dict:"作る", english:"to make", masu:"作ります", te:"作って", group:1},
  {dict:"旅行する", english:"to travel", masu:"旅行します", te:"旅行して", group:3},
  {dict:"払う", english:"to pay", masu:"払います", te:"払って", group:1},
  {dict:"働く", english:"to work", masu:"働きます", te:"働いて", group:1},
  {dict:"遊ぶ", english:"to play", masu:"遊びます", te:"遊んで", group:1},
  {dict:"すむ", english:"to live / to reside", masu:"すみます", te:"すんで", group:1},
  {dict:"写真を撮る", english:"to take a photo", masu:"写真を撮ります", te:"写真を撮って", group:1},
  {dict:"のぼる", english:"to climb", masu:"のぼります", te:"のぼって", group:1},
  {dict:"漬ける", english:"to soak / to pickle", masu:"漬けます", te:"漬けて", group:2},
  {dict:"かける", english:"to put on (sauce, dressing)", masu:"かけます", te:"かけて", group:2},
  {dict:"歩く", english:"to walk", masu:"歩きます", te:"歩いて", group:1},
  {dict:"使う", english:"to use", masu:"使います", te:"使って", group:1},
  {dict:"教える", english:"to teach", masu:"教えます", te:"教えて", group:2},
  {dict:"見せる", english:"to show", masu:"見せます", te:"見せて", group:2},
  {dict:"座る", english:"to sit", masu:"座ります", te:"座って", group:1},
  {dict:"急ぐ", english:"to hurry", masu:"急ぎます", te:"急いで", group:1},
  {dict:"浴びる", english:"to bathe / to take a shower", masu:"浴びます", te:"浴びて", group:2},
  {dict:"連絡する", english:"to contact", masu:"連絡します", te:"連絡して", group:3},
  {dict:"いう", english:"to say", masu:"いいます", te:"いって", group:1},
  {dict:"探す", english:"to search / to look for", masu:"探します", te:"探して", group:1},
  {dict:"訳す", english:"to translate", masu:"訳します", te:"訳して", group:1},
  {dict:"入る", english:"to enter", masu:"入ります", te:"入って", group:1},
  {dict:"借りる", english:"to borrow", masu:"借ります", te:"借りて", group:2},
  {dict:"持ってくる", english:"to bring (a thing)", masu:"持ってきます", te:"持ってきて", group:3},
  {dict:"連れてくる", english:"to bring (a person / animal)", masu:"連れてきます", te:"連れてきて", group:3},
  {dict:"タバコをすう", english:"to smoke (a cigarette)", masu:"タバコをすいます", te:"タバコをすって", group:1},
  {dict:"乗せる", english:"to put (an object) on", masu:"乗せます", te:"乗せて", group:2},
  {dict:"たずねる", english:"to ask", masu:"たずねます", te:"たずねて", group:2},
  {dict:"持っていく", english:"to take (things)", masu:"持っていきます", te:"持っていって", group:1},
  {dict:"連れていく", english:"to take (person / animal)", masu:"連れていきます", te:"連れていって", group:1}
];
